Repository CMPUT301F19T02/Vybe, pull requests merged in 2019-10, with the labels that each got.

#30 Create LICENSE
  LICENSE
Labels: documentation

#61 Add storyboard png
  doc/Storyboard.png
Labels: documentation

#67 add emoji pngs
  doc/Vibes/Emojis.zip
  doc/Vibes/anger.png
  doc/Vibes/clownery.png
  doc/Vibes/default.png
  doc/Vibes/disgust.png
  doc/Vibes/fear.png
  doc/Vibes/happy.png
  doc/Vibes/sad.png
  doc/Vibes/surprise.png
  doc/vybe.png
Labels: maintenence, wiki

#72 update doc to docs and add template files
  docs/ISSUE_TEMPLATE.md
  docs/MockupUI/01-login.png
  docs/MockupUI/02-your-vibes.png
  docs/MockupUI/03-add-vibe.png
  docs/MockupUI/04-view-vibe-details.png
  docs/MockupUI/05-edit-vibe.png
  docs/MockupUI/06-profile-page-personal.png
  docs/MockupUI/07-social-page-following.png
  docs/MockupUI/08-social-page-requests.png
  docs/MockupUI/09-map-page-personal.png
  docs/MockupUI/10-map-page-social.png
  docs/MockupUI/11-search-page-results.png
  docs/MockupUI/12-profile-page-other.png
  docs/MockupUI/13-signup.png
  docs/MockupUI/14-emostate-picker.png
  docs/PULL_REQUEST_TEMPLATE.md
  docs/Storyboard.png
  docs/Team.txt
  docs/UML.plantuml
  docs/UML.png
  docs/Vibes/Emojis.zip
  docs/Vibes/anger.png
  docs/Vibes/clownery.png
  docs/Vibes/default.png
  docs/Vibes/disgust.png
  docs/Vibes/fear.png
  docs/Vibes/happy.png
  docs/Vibes/sad.png
  docs/Vibes/surprise.png
  docs/vybe.png
Labels: maintenence
